# Generated by Django 5.1 on 2024-09-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
