# Generated by Django 5.1 on 2024-09-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_api', '0002_alter_course_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quantity',
            field=models.IntegerField(default=50),
        ),
    ]
