# Generated by Django 5.1 on 2024-09-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_user_password'),
        ('course_api', '0004_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(through='course_api.Enrollment', to='course_api.course'),
        ),
    ]
